version: '3.0'
services:
  server:
    build: ./
    image: davidvision/lbc_test
    environment:
      - MONGODB_URL=mongodb://mongo:27017/lbc-test-db
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
